"""
Virtual Machine (VM)
====================
Interprets quadruples generated by the compiler.
Executes operations with a program counter, memory store, and operation dispatcher.
"""

from utils.types import Type
import sys


class VirtualMachine:
    """
    Executes quadruples in a controlled manner with a program counter,
    memory store, and operation dispatcher.
    """

    def __init__(self, quadruples, symbols, memory, debug=False):
        """
        Initialize the VM with:
        - quadruples: QuadrupleList from compilation
        - symbols: SymbolTable with variable metadata
        - memory: VirtualMemory with address allocation and storage
        - debug: bool flag for debug output
        """
        self.quadruples = quadruples.all()
        self.symbols = symbols
        self.memory = memory
        self.debug = debug
        self.pc = 0  # Program counter
        self.output = []  # Captured output (for later introspection)

    def run(self):
        """Execute all quadruples from pc=0 until end or error."""
        if self.debug:
            print("\n===== VIRTUAL MACHINE EXECUTION =====\n")

        try:
            while self.pc < len(self.quadruples):
                quad = self.quadruples[self.pc]

                if self.debug:
                    print(
                        f"[PC={self.pc:04d}] {quad.op:6s} | L={quad.left} R={quad.right} Res={quad.result}"
                    )

                # Dispatch to appropriate handler
                self._execute_quadruple(quad)

                self.pc += 1

            if self.debug:
                print(
                    f"\n[PC={self.pc:04d}] PROGRAM HALT (reached end of instructions)"
                )

        except Exception as e:
            print(f"\n[RUNTIME ERROR at PC={self.pc}] {e}")
            if self.debug:
                print(f"Quadruple: {self.quadruples[self.pc]}")
            sys.exit(1)

    def _execute_quadruple(self, quad):
        """Dispatch quadruple to appropriate handler based on operator."""
        op = quad.op

        # Arithmetic operations
        if op == "+":
            self._op_add(quad.left, quad.right, quad.result)
        elif op == "-":
            self._op_subtract(quad.left, quad.right, quad.result)
        elif op == "*":
            self._op_multiply(quad.left, quad.right, quad.result)
        elif op == "/":
            self._op_divide(quad.left, quad.right, quad.result)
        elif op == "NEG":
            self._op_negate(quad.left, quad.result)

        # Relational operations
        elif op == "<":
            self._op_less_than(quad.left, quad.right, quad.result)
        elif op == "<=":
            self._op_less_equal(quad.left, quad.right, quad.result)
        elif op == ">":
            self._op_greater_than(quad.left, quad.right, quad.result)
        elif op == ">=":
            self._op_greater_equal(quad.left, quad.right, quad.result)
        elif op == "==":
            self._op_equal(quad.left, quad.right, quad.result)
        elif op == "!=":
            self._op_not_equal(quad.left, quad.right, quad.result)

        # Logical operations
        elif op == "and":
            self._op_and(quad.left, quad.right, quad.result)
        elif op == "or":
            self._op_or(quad.left, quad.right, quad.result)

        # Assignment
        elif op == ":=":
            self._op_assign(quad.left, quad.result)

        # Control flow
        elif op == "Goto":
            self._op_goto(quad.result)
        elif op == "GotoF":
            self._op_gotof(quad.left, quad.result)

        # I/O
        elif op == "Write":
            self._op_write(quad.left)

        else:
            raise ValueError(f"Unknown operation: {op}")

    # ======================================================================
    # ARITHMETIC OPERATIONS
    # ======================================================================

    def _op_add(self, left, right, result):
        """Addition: result = left + right"""
        left_val = self.memory.read(left)
        right_val = self.memory.read(right)

        if left_val is None or right_val is None:
            raise ValueError(f"Cannot add uninitialized values")

        sum_val = left_val + right_val
        self.memory.write(result, sum_val)

    def _op_subtract(self, left, right, result):
        """Subtraction: result = left - right"""
        left_val = self.memory.read(left)
        right_val = self.memory.read(right)

        if left_val is None or right_val is None:
            raise ValueError(f"Cannot subtract uninitialized values")

        diff_val = left_val - right_val
        self.memory.write(result, diff_val)

    def _op_multiply(self, left, right, result):
        """Multiplication: result = left * right"""
        left_val = self.memory.read(left)
        right_val = self.memory.read(right)

        if left_val is None or right_val is None:
            raise ValueError(f"Cannot multiply uninitialized values")

        prod_val = left_val * right_val
        self.memory.write(result, prod_val)

    def _op_divide(self, left, right, result):
        """Division: result = left / right"""
        left_val = self.memory.read(left)
        right_val = self.memory.read(right)

        if left_val is None or right_val is None:
            raise ValueError(f"Cannot divide uninitialized values")

        if right_val == 0:
            raise ValueError(f"Division by zero")

        div_val = left_val / right_val
        self.memory.write(result, div_val)

    def _op_negate(self, left, result):
        """Negate: result = -left"""
        left_val = self.memory.read(left)

        if left_val is None:
            raise ValueError(f"Cannot negate uninitialized value")

        neg_val = -left_val
        self.memory.write(result, neg_val)

    # ======================================================================
    # RELATIONAL OPERATIONS (all return bool)
    # ======================================================================

    def _op_less_than(self, left, right, result):
        """Less than: result = left < right"""
        left_val = self.memory.read(left)
        right_val = self.memory.read(right)

        if left_val is None or right_val is None:
            raise ValueError(f"Cannot compare uninitialized values")

        cmp_result = left_val < right_val
        self.memory.write(result, cmp_result)

    def _op_less_equal(self, left, right, result):
        """Less or equal: result = left <= right"""
        left_val = self.memory.read(left)
        right_val = self.memory.read(right)

        if left_val is None or right_val is None:
            raise ValueError(f"Cannot compare uninitialized values")

        cmp_result = left_val <= right_val
        self.memory.write(result, cmp_result)

    def _op_greater_than(self, left, right, result):
        """Greater than: result = left > right"""
        left_val = self.memory.read(left)
        right_val = self.memory.read(right)

        if left_val is None or right_val is None:
            raise ValueError(f"Cannot compare uninitialized values")

        cmp_result = left_val > right_val
        self.memory.write(result, cmp_result)

    def _op_greater_equal(self, left, right, result):
        """Greater or equal: result = left >= right"""
        left_val = self.memory.read(left)
        right_val = self.memory.read(right)

        if left_val is None or right_val is None:
            raise ValueError(f"Cannot compare uninitialized values")

        cmp_result = left_val >= right_val
        self.memory.write(result, cmp_result)

    def _op_equal(self, left, right, result):
        """Equal: result = left == right"""
        left_val = self.memory.read(left)
        right_val = self.memory.read(right)

        if left_val is None or right_val is None:
            raise ValueError(f"Cannot compare uninitialized values")

        cmp_result = left_val == right_val
        self.memory.write(result, cmp_result)

    def _op_not_equal(self, left, right, result):
        """Not equal: result = left != right"""
        left_val = self.memory.read(left)
        right_val = self.memory.read(right)

        if left_val is None or right_val is None:
            raise ValueError(f"Cannot compare uninitialized values")

        cmp_result = left_val != right_val
        self.memory.write(result, cmp_result)

    # ======================================================================
    # LOGICAL OPERATIONS
    # ======================================================================

    def _op_and(self, left, right, result):
        """Logical AND: result = left and right"""
        left_val = self.memory.read(left)
        right_val = self.memory.read(right)

        if not isinstance(left_val, bool) or not isinstance(right_val, bool):
            raise ValueError(f"Logical AND requires boolean operands")

        and_result = left_val and right_val
        self.memory.write(result, and_result)

    def _op_or(self, left, right, result):
        """Logical OR: result = left or right"""
        left_val = self.memory.read(left)
        right_val = self.memory.read(right)

        if not isinstance(left_val, bool) or not isinstance(right_val, bool):
            raise ValueError(f"Logical OR requires boolean operands")

        or_result = left_val or right_val
        self.memory.write(result, or_result)

    # ======================================================================
    # ASSIGNMENT
    # ======================================================================

    def _op_assign(self, left, result):
        """Assignment: result = left"""
        value = self.memory.read(left)

        if value is None:
            raise ValueError(f"Cannot assign uninitialized value")

        self.memory.write(result, value)

    # ======================================================================
    # CONTROL FLOW
    # ======================================================================

    def _op_goto(self, target):
        """Unconditional jump: pc = target"""
        self.pc = target - 1  # -1 because pc will be incremented after this quad

    def _op_gotof(self, condition_addr, target):
        """Conditional jump (false): if not condition, pc = target"""
        condition = self.memory.read(condition_addr)

        if not isinstance(condition, bool):
            raise ValueError(f"GotoF requires boolean condition")

        if not condition:
            self.pc = target - 1  # -1 because pc will be incremented after this quad

    # ======================================================================
    # I/O
    # ======================================================================

    def _op_write(self, value_addr):
        """Write: output value at value_addr"""
        value = self.memory.read(value_addr)

        if value is None:
            raise ValueError(f"Cannot write uninitialized value")

        # Convert to string for output
        output_str = str(value)

        # Print to stdout with newline
        print(output_str)
        self.output.append(output_str + "\n")

    # ======================================================================
    # DEBUG & INTROSPECTION
    # ======================================================================

    def dump_memory(self, segment=None):
        """Dump memory state for debugging."""
        print("\n=== MEMORY STATE ===")
        for addr, value in sorted(self.memory.memory_store.items()):
            seg, typ = self.memory.get_address_info(addr)
            if segment is None or seg == segment:
                print(f"  {addr:10d} ({seg:6s}, {typ.value:7s}): {value}")

    def get_output(self):
        """Get captured output."""
        return "".join(self.output)
